insert into team (name,season) values('ACK Stará Ves n. Ondøejnicí "A"',2010);
insert into team (name,season) values('ACK Stará Ves n. Ondøejnicí "B"',2010);
insert into team (name,season) values('bagbike',2010);
insert into team (name,season) values('Benefit cycling team',2010);
insert into team (name,season) values('CK FESO Petøvald'	,2010);
insert into team (name,season) values('CK Hobby Bohumín'  	,2010);
insert into team (name,season) values('CK Orlík Orlová 1'	,2010);
insert into team (name,season) values('CK Orlík Orlová 2'	,2010);
insert into team (name,season) values('CK Frenštát p.R. 1'	,2010);
insert into team (name,season) values('CK Frenštát p.R. 2'	,2010);
insert into team (name,season) values('Cyklo Star Cemo Mokrá'	,2010);
insert into team (name,season) values('Cyklokramo Suchdol n.O. "A"'	,2010);
insert into team (name,season) values('Cyklokramo Suchdol n.O. "B"'	,2010);
insert into team (name,season) values('Cyklosport Chropynì KTM'	,2010);
insert into team (name,season) values('Cyklosport Pøikryl,St.Ves n.O.'	,2010);
insert into team (name,season) values('Elektro Kubašta Chrudim'	,2010);
insert into team (name,season) values('Experiment 23'	,2010);
insert into team (name,season) values('Forman Cycling Team'	,2010);
insert into team (name,season) values('Galaxy Team Hranice'	,2010);
insert into team (name,season) values('HaF  Opava'	,2010);
insert into team (name,season) values('Kolosport-bc.cz'	,2010);
insert into team (name,season) values('LONGUS - DEXTER'	,2010);
insert into team (name,season) values('Max Cursor'	,2010);
insert into team (name,season) values('MH bike klub o.s. Havíøov'	,2010);
insert into team (name,season) values('Racing Olešná, F-M 1'	,2010);
insert into team (name,season) values('Racing Olešná, F-M 2'	,2010);
insert into team (name,season) values('Ridley'	,2010);
insert into team (name,season) values('SDH Stonava'	,2010);
insert into team (name,season) values('SK MADT-Sport Klapka'	,2010);
insert into team (name,season) values('SK Šafrata Bohumín'	,2010);
insert into team (name,season) values('SK Valašského království'	,2010);
insert into team (name,season) values('SKP Opava'	,2010);
insert into team (name,season) values('Studénka'	,2010);
insert into team (name,season) values('TiS - Vilhelm, F-M'	,2010);
insert into team (name,season) values('TJ Kolík Bohumín'	,2010);
insert into team (name,season) values('TJ TŽ Tøinec'	,2010);
insert into team (name,season) values('Triatlon klub Ostrava'	,2010);
insert into team (name,season) values('YOGI Racing Ostrava 1'	,2010);
insert into team (name,season) values('YOGI Racing Ostrava 2'	,2010);
